/run/initialize
/vis/open OGL

/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set gamma cyan
/vis/modeling/trajectories/drawByParticleID-0/set e- yellow
/vis/modeling/trajectories/drawByParticleID-0/set e+ red
/vis/modeling/trajectories/drawByParticleID-0/set neutron blue

/vis/drawVolume

/vis/scene/add/trajectories
/vis/scene/endOfEventAction accumulate
/vis/viewer/set/viewpointThetaPhi 90. 180.
#/vis/scene/add/axes 0 0 0 1 m
/vis/viewer/set/autoRefresh true

/run/beamOn 1
